### ISSUE TITLE
Undefined symbols ld error from nom

### ISSUE THREAD

**Issue by mwilliammyers** [Alexhuszagh/rust-lexical#29] opened 2019-10-25 01:54 UTC
Not sure if this is an issue with `lexical-core`, `nom`, `elastic-rs/elastic` (where I am using `nom`) or even `std`/`core` or the compiler but I thought I would start here...

I am getting `undefined symbols` `ld` errors for various symbols in `std`/`core` when I enable the `lexical` feature of `nom`. 

See elastic-rs/elastic/pull/389 for a little more background + error logs and [this](https://travis-ci.org/elastic-rs/elastic/jobs/602185150?utm_medium=notification&utm_source=github_status) or [this](https://travis-ci.org/elastic-rs/elastic/jobs/587715587?utm_medium=notification&utm_source=github_status) Travis build.

I have reproduced it on macOS 10.14 & 10.15 and Ubuntu 19.04 (and for the sake of completeness; various Linux via Docker) with `rustc 1.38.0 (625451e37 2019-09-23)`,  `1.39.0-beta.6 (224f0bc90 2019-10-15)`, `1.40.0-nightly (4a8c5b20c 2019-10-23)`—and a few other nightlies—and when cross compiling to `x86_64-unknown-linux-musl` from macOS and Linux hosts.

We don't actually use the `lexical` feature of `nom` in `elastic-rs/elastic`, so I disabled it and everything is building fine but I thought I would open this issue in case someone else runs into it.

I can also upload our current `Cargo.lock` if that would help...

**Comment by Alexhuszagh** [comment] 2020-01-06 19:12
@mwilliammyers This should be patched in the v0.6 branch of lexical-core, can you try this? I will submit a patch for nom, since they are still using v0.4 branch, which defines a C-API. I've since removed this functionality, since it increases the binary size, and causes linker errors due to some weird Rust compiler bug that's been difficult to reproduce.

**Comment by Alexhuszagh** [comment] 2020-02-26 18:37
Closed as of https://github.com/Geal/nom/pull/1101

**Closed by Alexhuszagh** 2020-02-26 18:37 UTC
Labels: downstream
