### ISSUE TITLE
This f64 value round-trips with 1 ULP error

### ISSUE THREAD

**Issue by dangrabcad** [Alexhuszagh/rust-lexical#20] opened 2019-07-24 15:51 UTC
Compile the following with lexical-core (I tried 0.4.0 and 0.4.2) with the default options:

```
extern crate lexical_core;

fn main() {
    let problematic: f64 = 7.689539722041643e164;
    let as_str: String = format!("{:?}", problematic); // or other formats, see below
    println!("{}", as_str);
    let lcresult = lexical_core::atof64_slice(as_str.as_bytes());
    println!("{:?}", lcresult);
    let parse_result: f64 = as_str.parse().unwrap();
    println!("{:?}", parse_result);
}
```

Output (I've removed most of the zeroes to make it more readable):
```
768953972204164300 … 0.0
768953972204164200 … 0.0
768953972204164300 … 0.0
```
Note the lexical-core result (middle) is different from the input value and from the `String::parse` result, by 1 ULP. I got the same error using `lexical::parse` (1.2.2) instead of `lexical_core::atof64_slice`. OTOH, I got the expected result if I replace the format in the marked line with `{}` (which omits the ".0") or with `{:e}` (which outputs `e164` like the input literal, instead of many zeroes). The input value has no special significance to me: I found it by testing my code (which calls into this function) using the proptest strategy `proptest::num::f64::NORMAL`.

**Comment by Alexhuszagh** [comment] 2019-07-24 23:45
Thank you for finding this, let me first confirm the issues compared to other parsers, and I'll triage it accordingly.

**Comment by Alexhuszagh** [comment] 2019-07-25 18:14
@dangrabcad This seems like an issue with the float formatter, which would be using an older version of ryu. Let me check this with the ryu formatter (the default float formatter). We are currently using an older version of ryu, so this may be patched currently. If not, this may be an issue I can raise there.

**Comment by Alexhuszagh** [comment] 2019-07-25 18:32
@dangrabcad Confirmed, it's a core error in the slow-path algorithm used by default, let me check if this exists in other versions.

Specifically, `bhcomp` is using a `b` value of `7.689539722041642e164`, and is using the internal routine `small_atof` to generate the significant digits. This is an amazing catch, thank you for finding this.

**Comment by Alexhuszagh** [comment] 2019-07-25 20:46
@dangrabcad I've confirmed the source of the issue, the scaling in `small_atof` is exactly 10 off for the real digits as opposed to the `b+h` digits, which is likely due to calculating the exponent in this case off-by-1 exactly. Should be an easy patch.

**Comment by Alexhuszagh** [comment] 2019-07-26 14:56
@dangrabcad The integration tests should fail (an unrelated bug I need to patch), but the following should fix the error. I've diagnosed the source of the issue, and it's a rather larger bug than I was hoping, and a very good catch. I'll add in more unittests to ensure this is never an issue again.

In short, any floating point-number with trailing 0s in the fraction part that forced the slow path (IE, more than 17 digits and near a halfway point) may have been rounded incorrectly. I'll be updating the README accordingly, crediting you for finding this, and adding in further tests to ensure this never happens again. I cannot thank you enough.

After patching the various dependency issues on older Rust versions (the issue with the integrations), I should push a commit later today.

Once again, thank you. Quite a catch.

**Comment by Alexhuszagh** [comment] 2019-07-26 23:37
Fixed as of v0.4.3.

**Closed by Alexhuszagh** 2019-07-26 23:37 UTC
Labels: bug, high

**Comment by plokhotnyuk** [comment] 2019-07-27 10:21
@Alexhuszagh I'm happy that the issue was caught and fixed so fast!

I've checked this case in [a simplified Scala implementation of your algorithm for base 10](https://github.com/plokhotnyuk/jsoniter-scala/blob/2a8cad7e550833d714b539a64413cc84e5302323/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1245-L1287) and found that it successfully passes through the medium path that uses a big lookup table (653 values of 64-bit coefficients) and one operation of 64-bit multiplication of mantissa.

Have you considered providing the specialized implementation for base 10?

For cases when you need to parse 64-bit float values that were previously serialized from the binary representation, it allows minimizing the need of subsequent slower paths down to 0.22% (for arbitrary binary representation).

**Comment by dangrabcad** [comment] 2019-07-30 10:10
Thanks for fixing this! I'm glad my bug report was so useful to you. It was really easy to find this edge case using proptest: it was the second or third test run that found it. If you like, I'd be happy to set up proptest to test lexical and lexical-core, and send you a PR. That way it should be easy to find any more values like this lurking in the corners.

**Comment by Alexhuszagh** [comment] 2019-07-30 17:50
@dangrabcad I already have some integrations for proptest, but clearly they aren't comprehensive enough. Please send over anything you have. This discovery sqaushed a class of bugs, and was beyond useful.

Also, @plokhotnyuk, I've been fairly swamped lately, but I would to. Also, I've been very glad my work has been useful to more than just the Rust ecosystem.
