### ISSUE TITLE
lexical::try_parse for floats parsing appears dependent on compiler flags 

### ISSUE THREAD

**Issue by rcarson3** [Alexhuszagh/rust-lexical#8] opened 2018-12-31 05:50 UTC
Hi,

First off I just want to thank you for the work you've put into this crate to create a faster parser of from string to uint, int, and floating types.

I'm currently writing a crate that I hope will eventually act as a faster version of numpy's loadtxt and genfromtxt but for Rust. The main logic can be found in the macro I wrote for the various different conversions as seen [here](https://github.com/rcarson3/rust_data_reader/blob/master/src/reader/macro_src.rs). The only lines I had to change to incorporate your crate can be found at [L172-188](https://github.com/rcarson3/rust_data_reader/blob/master/src/reader/macro_src.rs#L172-L188). The commented out lines are what used to be contained in the map function based on the standard library's conversion for most primitive types. 

The current tests I have fail for only the float cases. You can view them [here](https://github.com/rcarson3/rust_data_reader/blob/master/tests/test.rs#L288-L344). However, they pass for all of integer and unsigned integer tests. Now if I more or less copy exactly what's in the macro and run it outside of a macro it works. Below is an example:

```Rust
    let mut results = Vec::<f32>::new();
    let line_split_vec = vec!["1", "2", "3"];
    results.extend({
          line_split_vec.iter().map(|x| {
                lexical::try_parse::<f32, _>(x.trim()).unwrap()
           })
     });
    println!("{:?}", results);
``` 
I've also checked the type and values being fed into the ```lexical::try_parse```, and they are the same between my above example and the macro which fails.

edit:

I just ran it using the debug build and that works...

So, I've been fiddling around with the compiler options a bit, and it appears that depending on what compiler flags are being passed in determines whether or not it will run. I'll need to look a bit more into what was so different between what my basic cargo options set and the flags used for release.

**Comment by Alexhuszagh** [comment] 2019-01-01 21:57
That sounds like a bug, let me work on this. The behavior definitely should not depend on compiler flags, as the logic itself does not, so in that sense, this is definitely an issue. Thanks for raising this to my attention.

**Comment by rcarson3** [comment] 2019-01-27 18:44
It's fine and based on the [Cargo book](https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections) it looks like the debug flag could be tripping on some form of arithmetic overflow. I'm still surprised that this flag is turned on by default when the opt-level is set to 3 in your Cargo.toml.

**Comment by Alexhuszagh** [comment] 2019-01-28 15:15
It shouldn't be, since `debug = false` is set for both [release](https://github.com/Alexhuszagh/rust-lexical/blob/master/Cargo.toml#L147) and [bench](https://github.com/Alexhuszagh/rust-lexical/blob/master/Cargo.toml#L153) profiles.

**Comment by rcarson3** [comment] 2019-01-29 03:34
I guess I meant ```debug-assertions``` earlier. Nonetheless, it looks like Cargo might not be respecting the flags set in your Cargo.toml and is instead overriding it with whatever flags are set/used in the project's Cargo.toml that's using your crate. I'm wondering if this is then a bug with Cargo itself?

**Comment by saethlin** [comment] 2019-02-07 00:32
I just ran into this bug as well; I wanted to turn on debug-assertions and overflow-checks in a release binary and suddenly lexical started returning zeroes for nearly all the numbers I'm trying to parse. I've been using `lexical::parse` instead of `try_parse`, so this was... more annoying than I wish. Here's a program sufficient to reproduce the bug:

```
fn main() {
    let num: f64 = lexical::try_parse(b"5.002868148396374").unwrap();
}
```
And it must be compiled with both `opt-level=3` and `debug-assertions=true`.

The bug was introduced in 2.0. As this is pretty serious, I suggest yanking the 2.0 from crates.io.

**Comment by rcarson3** [comment] 2019-02-08 04:55
Since the parser seems to work when the ```debug-assertions``` flag is set to false, could a 0.0.1 bump release be made that contains a "debug" feature so float parsing defaults to the std library's implementation when that flag is set? I figure this might be an alright band-aid at least until a better bug fix can be figured out. It would allow people to test their code for overflow errors, and they could then benefit from the faster parser later on if they'd like.

**Comment by Alexhuszagh** [comment] 2019-02-12 18:57
I'm **still** not replicating this, sorry for the delay. I'm not yanking 2.0 from the release, but I am trying to fix this issue. This is not a memory safety issue, this is a potential regression for correctness.

`try_atof64_slice(b"5.002868148396374")` for lexical-core correctly returns a `Success` enum, and the lexical correctly returns `Ok(5.002868148396374)` from `lexical::try_parse::<f64, _>(b"5.002868148396374")`.

These have been added to 3fe9bd0fef5b32d6fb9fa2de27911d24c116dd29. Can I get a few, small, working examples that fail with the exact compiler flags or features you are using, @rcarson3 and @saethlin?

**Comment by Alexhuszagh** [comment] 2019-02-12 19:08
I've added 32-bit versions (for f32) just for good measure (in c3ed01225fa1881aed256937f2a24f712801b404), and will run the comprehensive tests for f64 with both debug-assertions on and off for good measure, but simple strings that fail and the compiler flags or features enabled would be hugely useful in debugging this. 

I've failed to reproduce this issue on my machine, so it's possible it depends on the machine? I have access to Windows and MacOS (the former through VMs, and the latter through an old laptop), however, I am running Linux. Any information would be useful.

**Comment by saethlin** [comment] 2019-02-12 19:28
I can reproduce this on an up-to-date Arch linux machine and an RHEL machine. I'll check in on Windows later today.

Cargo.toml
```
[package]
name = "scratch"
version = "0.1.0"

[dependencies]
lexical = "2.0"

[profile.release]
debug-assertions = true
```

src/main.rs
```
fn main() {
    let num: f64 = lexical::try_parse(b"5.002868148396374").unwrap();
}
```

rustc --version
```
rustc 1.32.0 (9fda7c223 2019-01-16)
```
cargo --version
```
cargo 1.32.0 (8610973aa 2019-01-02)
```

**Comment by saethlin** [comment] 2019-02-12 19:32
Here's the lexical parts of my Cargo.lock just in case we've got something funky going on there
```
[[package]]
name = "lexical"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cfg-if 0.1.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "lexical-core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "lexical-core"
version = "0.3.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cfg-if 0.1.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "ryu 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)",
 "stackvector 1.0.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "static_assertions 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

**Comment by Alexhuszagh** [comment] 2019-02-12 19:59
I've been using Cargo 1.31.0, so I'm updating now and going to report back. Thank you.

**Comment by rcarson3** [comment] 2019-02-13 03:00
I'm running Cargo and Rustc 1.31.1.

The example problem is:

```Rust
extern crate lexical;

fn main() {
    let mut results = Vec::<f32>::new();
    let line_split_vec = vec!["1", "2", "3"];
    results.extend({
          line_split_vec.iter().map(|x| {
                lexical::try_parse::<f32, _>(x.trim()).unwrap()
           })
     });
    println!("{:?}", results);
}
```

My Cargo.toml:

```Toml
[package]
name = "test_lexical"
version = "0.1.0"
authors = ["example"]
edition = "2018"

[dependencies]
lexical = "2.0.0"

[profile.release]
#Doesn't fail when this is set to 0. However, the debug-assertions option is
#not turned on when this is used
#When set to an opt-level of 1 the error says Illegal instruction (core dumped)
#opt-level >1 results in the following error:
#thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(InvalidDigit(0))'
opt-level = 3 
debug-assertions = true #This set to true causes it to fail
overflow-checks = true #This set to true doesn't
```

lexical and lexical-core are compiled with the following flags and features:

```
   Compiling lexical-core v0.3.1
 --color always --crate-type lib --crate-type staticlib --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C debug-assertions=on -C overflow-checks=off --cfg 'feature="correct"' --cfg 'feature="ryu"' --cfg 'feature="stackvector"' --cfg 'feature="std"' --cfg 'feature="table"'

   Compiling lexical v2.0.0
 --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C debug-assertions=on -C overflow-checks=off --cfg 'feature="correct"' --cfg 'feature="default"' --cfg 'feature="lexical-core"' --cfg 'feature="ryu"' --cfg 'feature="std"'--cap-lints allow`
```

**Comment by Alexhuszagh** [comment] 2019-02-13 18:54
Ok, finally able to reproduce this. For some reason, nothing was triggering with the built-in tests, so I developed a dummy crate and everything is reproducing. I should have a fix soon, and then a new version will be published shortly.

**Comment by Alexhuszagh** [comment] 2019-02-13 20:17
Fixed as of 4e0418d89fdb10807206958dad9f5162181b4fb4. Can both @rcarson3 and @saethlin confirm this?

**Comment by rcarson3** [comment] 2019-02-14 02:54
@Alexhuszagh I just tested this on my little toy problem, and it seems to be working now. Thanks for getting this fixed :)

**Comment by Alexhuszagh** [comment] 2019-02-14 16:28
Live as of [lexical v2.1](https://crates.io/crates/lexical/2.1.0) and [lexical-core v0.4](https://crates.io/crates/lexical-core/0.4.0).

**Closed by Alexhuszagh** 2019-02-14 16:28 UTC
Labels: bug
